version: "3.4"
services:
  db:
    image: postgres:14-bullseye
    container_name: bananagrams_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:9-alpine
    container_name: bananagrams_flyway
    command: -url=jdbc:postgresql://db/postgres -schemas=public -user=user
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
volumes:
  db:
    name: bananagrams_db
