name: Deploy Database

on:
  push:
    branches: [develop, main]
    paths:
      - "migrations/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download flyway
        run: wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.8.2/flyway-commandline-7.8.2-linux-x64.tar.gz
      - name: extract and link flyway
        run: tar -xvf flyway-commandline-7.8.2-linux-x64.tar.gz && sudo ln -s `pwd`/flyway-7.8.2/flyway /usr/local/bin
      - name: migrate
        # if: github.ref == 'refs/heads/main'
        run: flyway -url='${{ secrets.DEV_DB_URL }}' -user='${{ secrets.DEV_DB_USER }}' -password='${{ secrets.DEV_DB_PASSWORD }}' -locations=filesystem:./migrations/base -outOfOrder=true migrate
