name: Verify Infrastructure

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "iac/**"

defaults:
  run:
    working-directory: ./iac

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint -t ./**/*.yaml
